### ISSUE TITLE
Security Vulnerability - Action Required: Overflow vulnerability may occur in your project.

### ISSUE THREAD

**Issue by Crispy-fried-chicken** [SunBK201/umicat#2]
the function in `src/uct_upstream.c` which is shown below may have arithmetic overflow vulnerability.
```
static uct_inline uct_int_t
power(uct_int_t x, uct_int_t n)
{
    if (n == 0)
        return 1;
    int res = power(x, n / 2);
    if (n % 2 != 0)
        return res * res * x;
    else
        return res * res;
}
```

Multiplication result converted to larger type:  The code that converts the result of an integer multiplication to a larger type. Since the conversion applies after the multiplication, arithmetic overflow may still occur.

**Comment by SunBK201** [comment]
Thanks very much for checking code vulnerabilities! I have checked the code, it's definitely a confirmed overflow vulnerability. Feel free on creating pull request :)

**Comment by SunBK201** [comment]
Are you a robot?
